# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca469c6d0e637a5baf59eb16d0b434b58e6c024aadec405948a72cc5aabead3358f8b68c16a31378acccda499b4ffc62f7c3caa4093761b220f870cfb8b5724

test:
  secret_key_base: c19c3813a13133d5d2e823dabc0c0e366e40d98652de296487f896e87046237af3a6b34b856eb54898dd150b323d4bb3fa581bd73210d485eb0bedde42acd527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
